//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Identity.Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Identity.Recources.IdentityResources", typeof(IdentityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل مستخدم.
        /// </summary>
        public static string AccountCreateHeader {
            get {
                return ResourceManager.GetString("AccountCreateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        public static string AccountDashboard {
            get {
                return ResourceManager.GetString("AccountDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب موقوف.
        /// </summary>
        public static string AccountSuspended {
            get {
                return ResourceManager.GetString("AccountSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إيقاف حسابك من قبل مدير النظام.
        /// </summary>
        public static string AccountSuspendedDetails {
            get {
                return ResourceManager.GetString("AccountSuspendedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل مستخدم.
        /// </summary>
        public static string ActivateUser {
            get {
                return ResourceManager.GetString("ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد تفعيل المستخدم؟.
        /// </summary>
        public static string ActivateUserConfirm {
            get {
                return ResourceManager.GetString("ActivateUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء محاولة تفعيل المستخدم.
        /// </summary>
        public static string ActivateUserError {
            get {
                return ResourceManager.GetString("ActivateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل المستخدم بنجاح.
        /// </summary>
        public static string ActivateUserSuccess {
            get {
                return ResourceManager.GetString("ActivateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ بالمجلد النشط.
        /// </summary>
        public static string ActiveDirectoryError {
            get {
                return ResourceManager.GetString("ActiveDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم او كلمة المرور غير صحيحة في المجلد النشط.
        /// </summary>
        public static string ActiveDirectoryUserInvalidCredintials {
            get {
                return ResourceManager.GetString("ActiveDirectoryUserInvalidCredintials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم لم يتم تسجيله بواسطة مدير النظام.
        /// </summary>
        public static string ActiveDirectoryUserNotRegistered {
            get {
                return ResourceManager.GetString("ActiveDirectoryUserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة التفعيل.
        /// </summary>
        public static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة صلاحية للمستخدم.
        /// </summary>
        public static string AddUserToRole {
            get {
                return ResourceManager.GetString("AddUserToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير النظام.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعين مشرف للجمرك مسبقا.
        /// </summary>
        public static string AdminAlreadyAssignedToThisPort {
            get {
                return ResourceManager.GetString("AdminAlreadyAssignedToThisPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات المعينة.
        /// </summary>
        public static string AssignedRoles {
            get {
                return ResourceManager.GetString("AssignedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التحقق.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من تغيير كلمة المرور؟.
        /// </summary>
        public static string ChangePasswordConfirmMessage {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        public static string ChangePasswordSuccessfully {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط التفعيل انتهت صلاحيته.
        /// </summary>
        public static string CodeExpiredDate {
            get {
                return ResourceManager.GetString("CodeExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات التواصل.
        /// </summary>
        public static string CommunicationData {
            get {
                return ResourceManager.GetString("CommunicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقر هنا لإستكمال الملف الشخصى.
        /// </summary>
        public static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد البريد الإلكتروني.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت صلاحية رابط تفعيل الحساب. يجب إرسال رابط جديد لاستكمال عميلة تفعيل حسابك.
        /// </summary>
        public static string ConfirmEmailCodeExpired {
            get {
                return ResourceManager.GetString("ConfirmEmailCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط تفعيل الحساب غير صحيح. تأكد من البريد المرسل إليكم. يمكنك إعادة إرسال رابط جديد لتفعيل حسابك حال لم يعمل الرابط المرسل.
        /// </summary>
        public static string ConfirmEmailInvalidCode {
            get {
                return ResourceManager.GetString("ConfirmEmailInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تأكيد بريدكم الإلكتروني و تفعيل الحساب.
        /// </summary>
        public static string ConfirmEmailMsg {
            get {
                return ResourceManager.GetString("ConfirmEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد البريد الإلكتروني لايطابق البريد الإلكتروني.
        /// </summary>
        public static string ConfirmEmailNotMatchValidator {
            get {
                return ResourceManager.GetString("ConfirmEmailNotMatchValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تأكيد بريدك الإلكتروني بنجاح.
        /// </summary>
        public static string ConfirmEmailSuccess {
            get {
                return ResourceManager.GetString("ConfirmEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور الجديدة.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور لا يطابق كلمة المرور.
        /// </summary>
        public static string ConfirmPasswordNotMatchValidator {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatchValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضابط اتصال.
        /// </summary>
        public static string ContactOfficer {
            get {
                return ResourceManager.GetString("ContactOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string Contry {
            get {
                return ResourceManager.GetString("Contry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صلاحية.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم السجل التجاري المدخل مسجل لمستخدم آخر. أدخل رقم السجل التجاري مختلف .
        /// </summary>
        public static string CRNumberAlreadyExist {
            get {
                return ResourceManager.GetString("CRNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية غير صحيحة.
        /// </summary>
        public static string CurrentPasswordNotValid {
            get {
                return ResourceManager.GetString("CurrentPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيقاف مستخدم.
        /// </summary>
        public static string DeactivateUser {
            get {
                return ResourceManager.GetString("DeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد إيقاف المستخدم؟.
        /// </summary>
        public static string DeactivateUserConfirm {
            get {
                return ResourceManager.GetString("DeactivateUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء محاولة إيقاف المستخدم.
        /// </summary>
        public static string DeactivateUserError {
            get {
                return ResourceManager.GetString("DeactivateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب إيقاف المستخدم.
        /// </summary>
        public static string DeactivateUserReason {
            get {
                return ResourceManager.GetString("DeactivateUserReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إيقاف المستخدم بنجاح.
        /// </summary>
        public static string DeactivateUserSuccess {
            get {
                return ResourceManager.GetString("DeactivateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مستخدم.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف المستخدم؟.
        /// </summary>
        public static string DeleteUserConfirm {
            get {
                return ResourceManager.GetString("DeleteUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حذث خطأ أثناء محاولة حذف المستخدم.
        /// </summary>
        public static string DeleteUserError {
            get {
                return ResourceManager.GetString("DeleteUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم حذف المستخدم بنجاح..
        /// </summary>
        public static string DeleteUserSuccess {
            get {
                return ResourceManager.GetString("DeleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المستخدم.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل البريد الإلكتروني.
        /// </summary>
        public static string EditMyEmail {
            get {
                return ResourceManager.GetString("EditMyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بياناتي.
        /// </summary>
        public static string EditMyProfile {
            get {
                return ResourceManager.GetString("EditMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصلاحية.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات المستخدم.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مسجل في النظام. الرجاء إدخال بريد إلكترونى مختلف.
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد البريد الإلكتروني.
        /// </summary>
        public static string EmailConfirm {
            get {
                return ResourceManager.GetString("EmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد البريد الإلكتروني لا يطابق البريد الإلكتروني.
        /// </summary>
        public static string EmailConfirmNotMatchValidator {
            get {
                return ResourceManager.GetString("EmailConfirmNotMatchValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تأكيد الحساب بواسطة البريد الالكتروني.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رابط كلمة المرور.
        /// </summary>
        public static string EmailPasswordLink {
            get {
                return ResourceManager.GetString("EmailPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صحيح.
        /// </summary>
        public static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موظف.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال رمز التحقق.
        /// </summary>
        public static string EnterActivationCode {
            get {
                return ResourceManager.GetString("EnterActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   لغة الإدخال.
        /// </summary>
        public static string EntryLanguage {
            get {
                return ResourceManager.GetString("EntryLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاضر فعاليات.
        /// </summary>
        public static string EventSpeaker {
            get {
                return ResourceManager.GetString("EventSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبير.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول&lt;br /&gt;بحساب فيسبوك.
        /// </summary>
        public static string FacebookLogin {
            get {
                return ResourceManager.GetString("FacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول بالعربية.
        /// </summary>
        public static string FirstNameAr {
            get {
                return ResourceManager.GetString("FirstNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول بالإنجليزية.
        /// </summary>
        public static string FirstNameEn {
            get {
                return ResourceManager.GetString("FirstNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل نسيت كلمة المرور ؟.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فضلا تحقق من الرابط المرسل الى بريدكم الإلكتروني لإعادة تعيين كلمة المرور.
        /// </summary>
        public static string ForgetPasswordConfirmMsg {
            get {
                return ResourceManager.GetString("ForgetPasswordConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم كاملا.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالكامل بالعربية.
        /// </summary>
        public static string FullNameAr {
            get {
                return ResourceManager.GetString("FullNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالكامل بالإنجليزية.
        /// </summary>
        public static string FullNameEn {
            get {
                return ResourceManager.GetString("FullNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواطنى مجلس التعاون الخليجى.
        /// </summary>
        public static string GCC_Citizens {
            get {
                return ResourceManager.GetString("GCC_Citizens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك حساب !.
        /// </summary>
        public static string HasNoAccount {
            get {
                return ResourceManager.GetString("HasNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل المستشفى مطلوب .
        /// </summary>
        public static string HospitalIsRequired {
            get {
                return ResourceManager.GetString("HospitalIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية / الإقامة.
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم .
        /// </summary>
        public static string IdentityType {
            get {
                return ResourceManager.GetString("IdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مفعل.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الرمز المدخل غير صحيحة.
        /// </summary>
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود التحقق غير صحيح.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صحيح.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات المدخلة غير صحيحة .
        /// </summary>
        public static string InvalidInputData {
            get {
                return ResourceManager.GetString("InvalidInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية دخول غير صحيحة ، فضلا أعد المحاولة.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال غير صحيح.
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متغيرات غير صالحة .
        /// </summary>
        public static string InvalidParametersError {
            get {
                return ResourceManager.GetString("InvalidParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة مرور غير صحيحة.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidReCaptcha.
        /// </summary>
        public static string InvalidReCaptcha {
            get {
                return ResourceManager.GetString("InvalidReCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidToken.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة التفعيل .
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسمى الوظيفى.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير بالعربية.
        /// </summary>
        public static string LastNameAr {
            get {
                return ResourceManager.GetString("LastNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير بالإنجليزية.
        /// </summary>
        public static string LastNameEn {
            get {
                return ResourceManager.GetString("LastNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق مؤقت.
        /// </summary>
        public static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بالدخول بصلاحيات مستخدم.
        /// </summary>
        public static string LoginUserTitle {
            get {
                return ResourceManager.GetString("LoginUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل خروجك بنجاح.
        /// </summary>
        public static string LogoutSuccessfully {
            get {
                return ResourceManager.GetString("LogoutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة صلاحيات المستخدم.
        /// </summary>
        public static string ManageUserRoles {
            get {
                return ResourceManager.GetString("ManageUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العضوية.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الوسط.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثانى بالعربية.
        /// </summary>
        public static string MiddleNameAr {
            get {
                return ResourceManager.GetString("MiddleNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثانى بالإنجليزية.
        /// </summary>
        public static string MiddleNameEn {
            get {
                return ResourceManager.GetString("MiddleNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال مسجل في النظام بالفعل. للتسجيل اختر رقم آخر.
        /// </summary>
        public static string MobileAlreadyRegistered {
            get {
                return ResourceManager.GetString("MobileAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب الموافقة على الشروط والأحكـام.
        /// </summary>
        public static string MustAcceptAgreement {
            get {
                return ResourceManager.GetString("MustAcceptAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية أو الإقامة مسجل في النظام بالفعل. للتسجبل تأكد من الرقم.
        /// </summary>
        public static string NationalIdAlreadyRegistered {
            get {
                return ResourceManager.GetString("NationalIdAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني الجديد.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد أدخلت بريد إلكتروني مطابق لبريدك الحالي.
        /// </summary>
        public static string NewEmailSameAsCurrentEmail {
            get {
                return ResourceManager.GetString("NewEmailSameAsCurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال الجديد.
        /// </summary>
        public static string NewPhoneNumber {
            get {
                return ResourceManager.GetString("NewPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم جديد.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم جديد&lt;br /&gt;انضم إلينا.
        /// </summary>
        public static string NewUserJoinUs {
            get {
                return ResourceManager.GetString("NewUserJoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواطن غير سعودى.
        /// </summary>
        public static string NonSaudiCitizen {
            get {
                return ResourceManager.GetString("NonSaudiCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعيين صلاحيات بعد.
        /// </summary>
        public static string NoRolesAssigned {
            get {
                return ResourceManager.GetString("NoRolesAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منسق جهة.
        /// </summary>
        public static string OrganizationCoordinator {
            get {
                return ResourceManager.GetString("OrganizationCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        public static string Passwordchanged {
            get {
                return ResourceManager.GetString("Passwordchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;password-hint&quot;&gt;
        ///    &lt;li&gt;يجب أن تتراوح كلمة المرور بين 8 إلى 20 حرفًا&lt;/li&gt;
        ///    &lt;li&gt;يجب أن تحتوي كلمة المرور على رقم واحد على الأقل (&apos;0&apos; - &apos;9&apos;)&lt;/li&gt;
        ///    &lt;li&gt;يجب أن تحتوي كلمة المرور على أحرف صغيرة واحدة على الأقل (&apos;a&apos; - &apos;z&apos;)&lt;/li&gt;
        ///    &lt;li&gt;يجب أن تحتوي كلمة المرور على أحرف كبيرة واحدة على الأقل (&apos;A&apos; - &apos;Z&apos;)&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب أن تحتوى على أحرف صغيرة  &apos;a-z&apos;.
        /// </summary>
        public static string PasswordMustHaveLowerCase {
            get {
                return ResourceManager.GetString("PasswordMustHaveLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب أن تحتوى على أحرف كبيرة &apos;A-Z&apos;.
        /// </summary>
        public static string PasswordMustHaveUpperCase {
            get {
                return ResourceManager.GetString("PasswordMustHaveUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب أن تكون ما بين 8 إلى 20 حرف .
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير صالحة.
        /// </summary>
        public static string PasswordValidator {
            get {
                return ResourceManager.GetString("PasswordValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الشخصية.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال المدخل مسجل لمستخدم آخر. أدخل رقم جوال مختلف .
        /// </summary>
        public static string PhoneNumberAlreadyExist {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير الرقم بنجاح.
        /// </summary>
        public static string PhoneNumberChangedSuccessfully {
            get {
                return ResourceManager.GetString("PhoneNumberChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل الاسم كاملاً.
        /// </summary>
        public static string PleaseEnterFullName {
            get {
                return ResourceManager.GetString("PleaseEnterFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل رقم الهوية.
        /// </summary>
        public static string PleaseEnterNationalId {
            get {
                return ResourceManager.GetString("PleaseEnterNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة المفضلة للعرض و التواصل.
        /// </summary>
        public static string PreferredUiAndConnectionLanguage {
            get {
                return ResourceManager.GetString("PreferredUiAndConnectionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة المفضلة للعرض.
        /// </summary>
        public static string PreferredUiLanguage {
            get {
                return ResourceManager.GetString("PreferredUiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المستخدم.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بياناتي.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث بيانات الملف الشخصى.
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الحساب بنجاح, الرجاء مراجعة البريد الإلكتروني لتفعيل الحساب 
        ///وستصلك رسالة برمز للتحقق من رقم الجوال المسجل كذلك يمكنك تعديل رقم الجوال لاحقاً من صفحة الملف الشخصي.
        /// </summary>
        public static string RegisterationSuccess {
            get {
                return ResourceManager.GetString("RegisterationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم فرد.
        /// </summary>
        public static string RegisteredUser {
            get {
                return ResourceManager.GetString("RegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التسجيل من هنا بالضغط على الرابط أدناه.
        /// </summary>
        public static string RegisterHere {
            get {
                return ResourceManager.GetString("RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حساب.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء مستخدم جديد.
        /// </summary>
        public static string RegisterNewUserTitle {
            get {
                return ResourceManager.GetString("RegisterNewUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الحساب بنجاح, الرجاء مراجعة البريد الإلكتروني لتفعيل الحساب.
        /// </summary>
        public static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ازالة صلاحية المستخدم.
        /// </summary>
        public static string RemoveUserRole {
            get {
                return ResourceManager.GetString("RemoveUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من إزالة هذه الصلاحية عن المستخدم؟.
        /// </summary>
        public static string RemoveUserRoleConfirmMessage {
            get {
                return ResourceManager.GetString("RemoveUserRoleConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رمز التحقق.
        /// </summary>
        public static string RequiredCaptchaMessage {
            get {
                return ResourceManager.GetString("RequiredCaptchaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة إرسال رابط التفعيل.
        /// </summary>
        public static string ResendConfirmEmailLink {
            get {
                return ResourceManager.GetString("ResendConfirmEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين كلمة المرور.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد إعادة تعيين كلمة المرور.
        /// </summary>
        public static string ResetPasswordConfirm {
            get {
                return ResourceManager.GetString("ResetPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من إعادة تعيين كلمة المرور ؟.
        /// </summary>
        public static string ResetPasswordConfirmMessage {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تعيين كلمة المرور بنجاح فضلا اضغط على الرابط لإعادة الدخول.
        /// </summary>
        public static string ResetPasswordConfirmMsg {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط إعادة كلمة مرور غير صحيح. تأكد من البريد المرسل إليكم. يمكنك إعادة إرسال رابط جديد لإعادة تعيين كلمة المرور حال لم يعمل الرابط المرسل.
        /// </summary>
        public static string ResetPasswordInvalidCode {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير صحيحة.
        /// </summary>
        public static string ResetPasswordNotValid {
            get {
                return ResourceManager.GetString("ResetPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تعيين كلمة المرور بنجاح.
        /// </summary>
        public static string ResetPasswordSuccessfully {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز الصلاحية.
        /// </summary>
        public static string RoleCode {
            get {
                return ResourceManager.GetString("RoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اضافة الصلاحية الجديدة بنجاح.
        /// </summary>
        public static string RoleCreatedSuccessfully {
            get {
                return ResourceManager.GetString("RoleCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الصلاحية.
        /// </summary>
        public static string RoleDescription {
            get {
                return ResourceManager.GetString("RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الصلاحية بالعربي.
        /// </summary>
        public static string RoleDescriptionArabic {
            get {
                return ResourceManager.GetString("RoleDescriptionArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الصلاحية بالانجليزي.
        /// </summary>
        public static string RoleDescriptionEnglish {
            get {
                return ResourceManager.GetString("RoleDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الصلاحية.
        /// </summary>
        public static string RoleDetails {
            get {
                return ResourceManager.GetString("RoleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة الصلاحيات.
        /// </summary>
        public static string RoleGroup {
            get {
                return ResourceManager.GetString("RoleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصلاحية.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصلاحية بالعربي.
        /// </summary>
        public static string RoleNameArabic {
            get {
                return ResourceManager.GetString("RoleNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصلاحية بالانجليزي.
        /// </summary>
        public static string RoleNameEnglish {
            get {
                return ResourceManager.GetString("RoleNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دور العمل.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string SamAccountName {
            get {
                return ResourceManager.GetString("SamAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواطن سعودى.
        /// </summary>
        public static string SaudiCitizen {
            get {
                return ResourceManager.GetString("SaudiCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حفظ التغيرات؟.
        /// </summary>
        public static string SaveChangesConfirm {
            get {
                return ResourceManager.GetString("SaveChangesConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة إرسال بريد التفعيل .
        /// </summary>
        public static string SendConfirmUserEmail {
            get {
                return ResourceManager.GetString("SendConfirmUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد إعادة إرسال بريد التفعيل للمستخدم؟.
        /// </summary>
        public static string SendConfirmUserEmailConfirm {
            get {
                return ResourceManager.GetString("SendConfirmUserEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء محاولة إرسال بريد التفعيل للمستخدم.
        /// </summary>
        public static string SendConfirmUserEmailError {
            get {
                return ResourceManager.GetString("SendConfirmUserEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إرسال بريد التفعيل للمستخدم بنجاح.
        /// </summary>
        public static string SendConfirmUserEmailSuccess {
            get {
                return ResourceManager.GetString("SendConfirmUserEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رابط التفعيل.
        /// </summary>
        public static string SendedActivationLink {
            get {
                return ResourceManager.GetString("SendedActivationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال بريد إلكتروني.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة النظام.
        /// </summary>
        public static string SystemManagement {
            get {
                return ResourceManager.GetString("SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموافقة على الشروط والأحكـام.
        /// </summary>
        public static string TermsAgreement {
            get {
                return ResourceManager.GetString("TermsAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب الموافقة على الشروط والأحكام.
        /// </summary>
        public static string TermsAgreementMustBeTrue {
            get {
                return ResourceManager.GetString("TermsAgreementMustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكـام.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجد بالعربية.
        /// </summary>
        public static string ThirdNameAr {
            get {
                return ResourceManager.GetString("ThirdNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجد بالإنجليزية.
        /// </summary>
        public static string ThirdNameEn {
            get {
                return ResourceManager.GetString("ThirdNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرب.
        /// </summary>
        public static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار لغة الإدخال.
        /// </summary>
        public static string TranslatorMustSelectEntryLangauge {
            get {
                return ResourceManager.GetString("TranslatorMustSelectEntryLangauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول&lt;br /&gt;بحساب تويتر.
        /// </summary>
        public static string TwitterLogin {
            get {
                return ResourceManager.GetString("TwitterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موظف.
        /// </summary>
        public static string Unemployed {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات الصلاحية بنجاح.
        /// </summary>
        public static string UpdateRoleSuccessfully {
            get {
                return ResourceManager.GetString("UpdateRoleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات المستخدم بنجاح.
        /// </summary>
        public static string UpdateUserSuccessfully {
            get {
                return ResourceManager.GetString("UpdateUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لإعادة إرسال رابط التفعيل لبريدك الإلكتروني اضغط هنا.
        /// </summary>
        public static string UrlActivationTitle {
            get {
                return ResourceManager.GetString("UrlActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل حساب المستخدم من قبل.
        /// </summary>
        public static string UserAlreadyActivated {
            get {
                return ResourceManager.GetString("UserAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعين المستخدم لدور مسبقا.
        /// </summary>
        public static string UserAlreadyAssignedToRole {
            get {
                return ResourceManager.GetString("UserAlreadyAssignedToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف المستخدم. السبب:.
        /// </summary>
        public static string UserCanNotBeDeleted {
            get {
                return ResourceManager.GetString("UserCanNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن للمستخدم تعديل حالة التفعيل الخاصة به.
        /// </summary>
        public static string UserCanNotChangeHisStatus {
            get {
                return ResourceManager.GetString("UserCanNotChangeHisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة المستخدم بنجاح.
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المستخدم.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات المستخدم بنجاح.
        /// </summary>
        public static string UserDetailsUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserDetailsUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إيقاف المستخدم ، الرجاء التواصل مع مدير النظام.
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم ليس لديه صلاحية لهذا المحتوى.
        /// </summary>
        public static string UserIsNotAuthourized {
            get {
                return ResourceManager.GetString("UserIsNotAuthourized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم مسجل في النظام بالفعل. للتسجيل اختر اسم مستخدم مختلف.
        /// </summary>
        public static string UserNameAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserNameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو البريد الالكتروني.
        /// </summary>
        public static string UserNameOrEmail {
            get {
                return ResourceManager.GetString("UserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم غير صحيح.
        /// </summary>
        public static string UserNameValidator {
            get {
                return ResourceManager.GetString("UserNameValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إيقاف المستخدم من قبل مدير النظام.
        /// </summary>
        public static string UserNotActivated {
            get {
                return ResourceManager.GetString("UserNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المستخدم بالنظام.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم مسجل في النظام بالفعل. للتسجيل اختر رقم مستخدم مختلف.
        /// </summary>
        public static string UserNumberAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserNumberAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المستخدمين.
        /// </summary>
        public static string UsersCount {
            get {
                return ResourceManager.GetString("UsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين في الصلاحية.
        /// </summary>
        public static string UsersInRole {
            get {
                return ResourceManager.GetString("UsersInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في انتظار تأكيد البريد.
        /// </summary>
        public static string WaitingConfirmation {
            get {
                return ResourceManager.GetString("WaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إرسال رسالة على بريدك الإلكترونى لتأكيد تفعيل حسابك على النظام  برجاء الضغط على الرابط المرفق لديكم فى الرسالة لتأكيد الحساب.
        /// </summary>
        public static string WaitingConfirmationMessage {
            get {
                return ResourceManager.GetString("WaitingConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إرسال رسالة على بريدك الإلكترونى الجديد لتأكيد صحة البيانات برجاء الضغط على الرابط المرفق لديكم فى الرسالة لتأكيد البريد الإلكتروني الجديد.
        /// </summary>
        public static string WaitingEmailConfirmationMessage {
            get {
                return ResourceManager.GetString("WaitingEmailConfirmationMessage", resourceCulture);
            }
        }
    }
}
